-- MySQL Script generated by MySQL Workbench
-- Thu Aug  4 14:38:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema homines
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema homines
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homines` DEFAULT CHARACTER SET utf8 ;
USE `homines` ;

-- -----------------------------------------------------
-- Table `homines`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homines`.`employee` (
  `id` BIGINT(60) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `birthday` DATE NULL,
  `email` VARCHAR(45) NULL,
  `personal_email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `classes` VARCHAR(45) NULL,
  `siape` VARCHAR(60) NOT NULL,
  `functions` VARCHAR(45) NULL,
  `degree` VARCHAR(45) NULL,
  `stand` VARCHAR(45) NULL,
  `sector` VARCHAR(45) NULL,
  `entry_date` DATE NULL,
  `departure_date` DATE NULL,
  `substitute_of` VARCHAR(45) NULL,
  `post` VARCHAR(45) NULL,
  `frequency` VARCHAR(45) NULL,
  `career` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homines`.`vacation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homines`.`vacation` (
  `id` BIGINT(60) NOT NULL AUTO_INCREMENT,
  `year` INT NOT NULL,
  `period1date_begin` DATE NULL,
  `period1date_end` DATE NULL,
  `period2date_begin` DATE NULL,
  `period2date_end` DATE NULL,
  `period3date_begin` DATE NULL,
  `period3date_end` DATE NULL,
  `employee_id` BIGINT(60) NOT NULL,
  PRIMARY KEY (`id`, `employee_id`),
  INDEX `fk_vacation_employeer_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_vacation_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `homines`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homines`.`ordinance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homines`.`ordinance` (
  `id` BIGINT(60) NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `ordinance` VARCHAR(45) NULL,
  `subject` VARCHAR(45) NOT NULL,
  `post` VARCHAR(45) NULL,
  `employee_id` BIGINT(60) NOT NULL,
  PRIMARY KEY (`id`, `employee_id`),
  INDEX `fk_ordinance_employee_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_ordinance_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `homines`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homines`.`probationary_stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homines`.`probationary_stage` (
  `id` BIGINT(60) NOT NULL AUTO_INCREMENT,
  `first_avaliation_date_begin` DATE NULL,
  `first_avaliation_date_end` DATE NULL,
  `second_avaliation_date_begin` DATE NULL,
  `second_avaliation_date_end` DATE NULL,
  `third_avaliation_date_begin` DATE NULL,
  `third_avaliation_date_end` DATE NULL,
  `employee_id` BIGINT(60) NOT NULL,
  PRIMARY KEY (`id`, `employee_id`),
  INDEX `fk_probationary_stage_employee_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_probationary_stage_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `homines`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homines`.`progression`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homines`.`progression` (
  `id` BIGINT(60) NOT NULL AUTO_INCREMENT,
  `actual_level` VARCHAR(45) NULL,
  `next_level` VARCHAR(45) NULL,
  `last_progression_date` DATE NULL,
  `next_progression_date` DATE NULL,
  `progression_month` VARCHAR(45) NOT NULL,
  `employee_id` BIGINT(60) NOT NULL,
  PRIMARY KEY (`id`, `employee_id`),
  INDEX `fk_progression_employee_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_progression_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `homines`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `homines`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homines`.`user` (
  `id` BIGINT(60) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;